name: CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'aeco.sln'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        with:
          nuget-version: 6.x

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Restore dependencies
        run: nuget restore $SOLUTION
      
      - name: Get version from tag
        run: | 
          VERSION=${{github.ref_name}}
          echo "VERSION=${VERSION:1}" >> $GITHUB_ENV

      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=$VERSION --no-restore

      - name: Run tests
        run: dotnet test /p:Configuration=$BUILD_CONFIG --no-restore --no-build --verbosity normal
        
      - name: Publish
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}

      - name: Create tag artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{github.ref_name}}
          path: Release